from __future__ import annotations

from src.features.sea.bottle.bottle_entity import BottleEntity

SEED_SENTINEL = "__seeded_bottle__"

BOTTLE_MESSAGES = [
    # Inspiration & Motivation (1-40)
    "Hạnh phúc không phải là đích đến, mà là hành trình chúng ta đang đi.",
    "Đôi khi, việc buông bỏ là cách tốt nhất để tìm lại chính mình.",
    "Cuộc sống giống như đi xe đạp. Để giữ thăng bằng, bạn phải tiếp tục di chuyển.",
    "Giữa bao la biển cả, hy vọng bạn tìm thấy bình yên trong tâm hồn.",
    "Đừng chờ đợi cơ hội, hãy tự tạo ra nó.",
    "Mỗi ngày mới là một cơ hội để bắt đầu lại.",
    "Sự tử tế là ngôn ngữ mà người điếc có thể nghe và người mù có thể thấy.",
    "Hãy sống như thể không có ngày mai.",
    "Điều tuyệt vời nhất thường đến khi bạn ít mong đợi nhất.",
    "Thất bại chỉ là cơ hội để bắt đầu lại một cách thông minh hơn.",
    "Đừng so sánh chương 1 của bạn với chương 20 của người khác.",
    "Sức mạnh không đến từ những gì bạn có thể làm, nó đến từ việc vượt qua những điều bạn nghĩ mình không thể.",
    "Hãy là phiên bản tốt nhất của chính mình, không phải bản sao của người khác.",
    "Mọi cơn bão rồi sẽ qua, và cầu vồng sẽ xuất hiện.",
    "Kiên nhẫn là chìa khóa của mọi thành công.",
    "Đừng để nỗi sợ hãi ngăn cản bạn làm điều mình yêu thích.",
    "Hạnh phúc là khi bạn biết trân trọng những gì mình đang có.",
    "Yêu thương cho đi là yêu thương còn mãi.",
    "Hãy cười nhiều hơn, vì cuộc đời quá ngắn để buồn phiền.",
    "Những điều tốt đẹp cần thời gian.",
    "Đừng bỏ cuộc, vì phép màu thường xảy ra vào phút chót.",
    "Tâm tĩnh lặng, đời an nhiên.",
    "Hãy làm việc chăm chỉ trong im lặng, để thành công lên tiếng thay bạn.",
    "Không có con đường nào trải đầy hoa hồng.",
    "Thái độ quyết định tất cả.",
    "Mỗi khó khăn đều mang trong mình hạt giống của cơ hội.",
    "Hãy biết ơn những gì bạn đang có, trước khi mong cầu những điều xa vời.",
    "Sự khác biệt duy nhất giữa một ngày tốt lành và một ngày tồi tệ là thái độ của bạn.",
    "Đừng để ngày hôm qua chiếm quá nhiều thời gian của ngày hôm nay.",
    "Bạn sinh ra là một nguyên bản, đừng chết như một bản sao.",
    "Hãy tin rằng bạn có thể, và bạn đã đi được một nửa chặng đường.",
    "Khó khăn không trường tồn, chỉ có con người bản lĩnh mới trường tồn.",
    "Đừng đếm những ngày trôi qua, hãy làm cho những ngày ấy trở nên đáng giá.",
    "Khi bạn muốn bỏ cuộc, hãy nhớ lại lý do khiến bạn bắt đầu.",
    "Cuộc sống không phải là chờ đợi bão đi qua, mà là học cách nhảy múa dưới mưa.",
    "Hạnh phúc không phải là có tất cả mọi thứ, mà là tận hưởng những gì bạn có.",
    "Gieo suy nghĩ, gặt hành động. Gieo hành động, gặt thói quen.",
    "Đừng sợ thất bại, hãy sợ việc dậm chân tại chỗ.",
    "Tương lai phụ thuộc vào những gì bạn làm ngày hôm nay.",
    "Hãy luôn giữ khuôn mặt hướng về ánh mặt trời, và bóng tối sẽ ngả về phía sau bạn.",

    # Love & Relationships (41-80)
    "Yêu là tìm thấy hạnh phúc của mình trong hạnh phúc của người khác.",
    "Tình yêu không cần phải hoàn hảo, nó chỉ cần là thật.",
    "Gửi người lạ, mong bạn luôn được yêu thương.",
    "Nếu bạn đang đọc tin nhắn này, hãy nhớ rằng bạn xứng đáng được yêu.",
    "Đôi khi người ta gặp nhau chỉ để lướt qua nhau.",
    "Tình yêu đích thực không có kết thúc có hậu, vì nó không bao giờ kết thúc.",
    "Hãy yêu bản thân mình trước khi yêu người khác.",
    "Đừng khóc vì nó đã kết thúc, hãy cười vì nó đã xảy ra.",
    "Người phù hợp sẽ đến vào đúng thời điểm.",
    "Một cái ôm ấm áp gửi đến bạn từ bên kia đại dương.",
    "Có những người gặp gỡ đã là một cái duyên, nhưng ở lại được hay không là do lòng người.",
    "Tình yêu là khi bạn nhìn vào mắt ai đó và thấy cả thế giới.",
    "Đừng vội vã, cái gì của mình thì sẽ là của mình.",
    "Đôi khi, khoảng cách là liều thuốc thử tốt nhất cho tình yêu.",
    "Hạnh phúc không phải là tìm được người hoàn hảo, mà là học cách yêu thương người không hoàn hảo một cách trọn vẹn.",
    "Tình yêu chân thành bắt đầu từ những điều giản dị nhất.",
    "Hãy trân trọng người luôn bên cạnh bạn những lúc khó khăn nhất.",
    "Đừng yêu ai đó vì ngoại hình, hãy yêu vì trái tim họ.",
    "Tình yêu không phải là sở hữu, mà là sự tự do cùng nhau.",
    "Có ai đó đang nhớ về bạn ngay lúc này.",
    "Đừng để quá khứ làm ảnh hưởng đến tình yêu hiện tại.",
    "Hãy dũng cảm để yêu thương một lần nữa.",
    "Mỗi cuộc gặp gỡ trong đời đều có ý nghĩa của nó.",
    "Tình yêu là phép màu chữa lành mọi vết thương.",
    "Hãy để trái tim dẫn đường, nhưng đừng quên mang theo lý trí.",
    "Đôi mắt không biết nói dối, hãy nhìn sâu vào đó.",
    "Tình yêu giống như gió, bạn không thể thấy nhưng có thể cảm nhận.",
    "Gặp đúng người, sai thời điểm là niềm đau. Gặp sai người, đúng thời điểm là bi kịch.",
    "Hạnh phúc trong tình yêu không phải là không có cãi vã, mà là sau mỗi lần cãi vã lại yêu nhau nhiều hơn.",
    "Đừng tìm kiếm tình yêu, hãy để tình yêu tìm thấy bạn.",
    "Một tin nhắn quan tâm đúng lúc có thể cứu rỗi cả một ngày tồi tệ.",
    "Yêu thương không cần lời nói, chỉ cần hành động.",
    "Trong tình yêu, sự tin tưởng quan trọng hơn tất cả.",
    "Hãy yêu như chưa từng bị tổn thương.",
    "Có những nỗi nhớ không thể gọi tên.",
    "Tình yêu là sự hy sinh thầm lặng.",
    "Đừng bao giờ hối tiếc vì đã yêu thương ai đó hết lòng.",
    "Tình yêu là thứ duy nhất nhân lên khi ta chia sẻ.",
    "Người yêu bạn thật lòng sẽ không bao giờ buông tay.",
    "Cảm ơn vì đã xuất hiện trong cuộc đời tôi.",

    # Humor & Fun (81-120)
    "Nếu cuộc đời ném cho bạn trái chanh, hãy gọi thêm tequila và muối!",
    "Hôm nay tôi chạy bộ. À không, là chạy trốn deadlines.",
    "Đang tìm kiếm người thất lạc: Động lực làm việc. Ai thấy xin trả lại.",
    "Người ta bảo tiền không mua được hạnh phúc, nhưng mua được trà sữa.",
    "Thức khuya mới biết đêm dài, thất tình mới biết... thôi đi ngủ!",
    "Bí mật của sự thành công là... tôi cũng chưa biết nữa.",
    "Cuộc đời thật bất công, tại sao đồ ngon lại toàn calo cao?",
    "Đang trôi dạt trên biển, ai cứu vớt tâm hồn ăn uống này với.",
    "Nụ cười là liều thuốc bổ, nhưng cười một mình thì coi chừng bị bắt.",
    "Hôm nay là một ngày tuyệt vời để... không làm gì cả.",
    "Tiền không tự sinh ra và mất đi, nó chỉ chuyển từ túi chồng sang túi vợ.",
    "Đừng bao giờ cãi nhau với kẻ ngốc, họ sẽ kéo bạn xuống trình độ của họ và thắng bằng kinh nghiệm.",
    "Thanh xuân như một tách trà, ăn xong miếng bánh hết bà thanh xuân.",
    "Cố tình trồng hoa hoa không nở, vô tình đi ngủ mỡ lại tăng.",
    "Yêu nhau mấy núi cũng trèo, hết yêu mấy bước đi vèo là xong.",
    "Đời là bể khổ, qua được bể khổ là qua đời.",
    "Trăm năm trong cõi người ta, cái gì không biết thì tra Google.",
    "Học không chơi đánh rơi tuổi trẻ, chơi không học bán rẻ tương lai.",
    "Tình yêu như bát bún riêu, bao nhiêu sợi bún bấy nhiêu sợi tình.",
    "Giang hồ hiểm ác không bằng mạng lag thất thường.",
    "Tiền thì không thiếu, nhưng nhiều thì không có.",
    "Kẻ thù lớn nhất của đời người là cái bụng đói.",
    "Đã ngu lại còn tỏ ra nguy hiểm.",
    "Sống đơn giản cho đời thanh thản.",
    "Ăn quả nhớ kẻ trồng cây, ăn đêm nhớ kẻ bán mì.",
    "Đừng buồn vì bạn xấu, hãy tin rằng bạn có một vẻ đẹp tiềm ẩn chưa tìm thấy.",
    "Mập đẹp, ốm dễ thương, lòi xương dễ mến.",
    "Vạn sự khởi đầu nan, gian nan bắt đầu nản.",
    "Nhà sạch thì mát, bát sạch thì... đỡ phải rửa.",
    "Chưa thấy quan tài chưa đổ lệ, chưa thấy bài thi chưa học bài.",
    "Không làm mà muốn có ăn thì chỉ có... ăn bám.",
    "Đường tình em thua, đường đua em chấp.",
    "Ế là xu thế, nên hãy cứ ế đi.",
    "Yêu đương gì tầm này, lo mà kiếm tiền đi.",
    "Muốn ngồi ở vị trí không ai ngồi được thì phải chịu cảm giác... đau mông.",
    "Xăng tăng giá, lương đứng yên, tình duyên lận đận.",
    "Dạo này trí nhớ kém quá, cứ nhớ mỗi mình em.",
    "Nhiều khi muốn làm người tốt, mà dòng đời xô đẩy làm người... ăn hại.",
    "Cuộc sống ngắn ngủi, hãy ăn món tráng miệng trước.",
    "Đừng để công việc giết chết bạn, hãy để... deadline làm điều đó.",

    # Life & Experience (121-160)
    "Cố lên, bạn đã làm rất tốt rồi!",
    "Hãy uống đủ nước và ngủ đủ giấc nhé.",
    "Một ngày tồi tệ không có nghĩa là cuộc đời tồi tệ.",
    "Hít thở sâu. Mọi chuyện rồi sẽ ổn thôi.",
    "Bạn mạnh mẽ hơn bạn nghĩ rất nhiều.",
    "Hôm nay hãy làm một điều gì đó tốt đẹp cho bản thân.",
    "Đừng so sánh bản thân với người khác, hãy so sánh với chính mình ngày hôm qua.",
    "Mọi nỗ lực của bạn sẽ được đền đáp xứng đáng.",
    "Hãy tin vào trực giác của bạn.",
    "Thế giới này cần nụ cười của bạn.",
    "Sức khỏe là vàng, hãy trân trọng nó.",
    "Thời gian là tài sản quý giá nhất, đừng lãng phí nó.",
    "Gia đình là nơi cuộc sống bắt đầu và tình yêu không bao giờ kết thúc.",
    "Bạn bè là những người thân mà ta tự chọn.",
    "Đủ nắng hoa sẽ nở, đủ yêu thương hạnh phúc sẽ đong đầy.",
    "Cuộc sống quá ngắn để ghét bỏ ai đó.",
    "Hãy tha thứ cho bản thân vì những lỗi lầm trong quá khứ.",
    "Học cách nói 'không' với những điều không phục vụ sự phát triển của bạn.",
    "Đọc sách là cách rẻ nhất để đi du lịch.",
    "Đừng ngại thay đổi, đó là quy luật của cuộc sống.",
    "Kỷ luật là cầu nối giữa mục tiêu và thành tựu.",
    "Hãy lắng nghe nhiều hơn và nói ít đi.",
    "Sự bình yên nằm trong tâm hồn, không phải ở ngoại cảnh.",
    "Đừng để mạng xã hội điều khiển cuộc sống của bạn.",
    "Hãy dành thời gian cho những người thực sự quan trọng.",
    "Tiền bạc là phương tiện, không phải mục đích sống.",
    "Lòng biết ơn biến những gì ta có thành 'đủ'.",
    "Cô đơn không đáng sợ, đáng sợ là ở bên cạnh người khiến mình cô đơn.",
    "Hãy sống trọn vẹn từng khoảnh khắc.",
    "Đôi khi, im lặng là câu trả lời tốt nhất.",
    "Sự thật có thể làm tổn thương nhất thời, nhưng dối trá làm tổn thương mãi mãi.",
    "Tôn trọng người khác là tôn trọng chính mình.",
    "Hãy giữ lời hứa, dù là nhỏ nhất.",
    "Đừng bao giờ đánh mất hy vọng.",
    "Mỗi người ta gặp đều biết một điều gì đó mà ta không biết.",
    "Hãy học cách chấp nhận những điều không thể thay đổi.",
    "Cuộc sống là những lựa chọn, hãy chọn niềm vui.",
    "Đừng sợ già đi, đó là đặc ân mà nhiều người không có được.",
    "Hãy gieo lòng tốt, bạn sẽ gặt hái hạnh phúc.",
    "Kết thúc mỗi ngày bằng một suy nghĩ tích cực.",

    # Facts & Random Thoughts (161-200)
    "Bạn có biết: Cá heo ngủ nhưng vẫn mở một mắt?",
    "Mật ong là thực phẩm duy nhất không bao giờ hỏng.",
    "Trái tim của tôm nằm ở trên đầu.",
    "Bạn không thể tự liếm khuỷu tay của mình.",
    "Ốc sên có thể ngủ liền 3 năm.",
    "Tại sao bánh pizza hình tròn lại được đựng trong hộp hình vuông và ăn theo hình tam giác?",
    "Nếu bạn hét liên tục trong 8 năm, 7 tháng và 6 ngày, bạn sẽ tạo ra đủ năng lượng để hâm nóng một tách cà phê.",
    "Trung bình mỗi người dành 6 tháng trong cuộc đời để chờ đèn đỏ.",
    "Kỷ lục thời gian bay dài nhất của một con gà là 13 giây.",
    "Tên của tất cả các lục địa đều bắt đầu và kết thúc bằng cùng một chữ cái (trong tiếng Anh).",
    "Bạn có đang cầm điện thoại bằng tay phải không?",
    "Hôm nay bạn đã cười chưa?",
    "Nếu được ước một điều, bạn sẽ ước gì?",
    "Đừng quên nhìn lên bầu trời đêm nay, có thể có sao băng đấy.",
    "Bạn thích chó hay mèo hơn?",
    "Màu yêu thích của bạn là gì?",
    "Bài hát nào khiến bạn khóc?",
    "Bộ phim hay nhất bạn từng xem là gì?",
    "Nếu ngày mai là tận thế, bạn sẽ làm gì hôm nay?",
    "Bạn có tin vào người ngoài hành tinh không?",
    "Món ăn ngon nhất bạn từng ăn là gì?",
    "Nơi nào bạn muốn đi du lịch nhất?",
    "Ai là người có ảnh hưởng lớn nhất đến cuộc đời bạn?",
    "Kỷ niệm đáng nhớ nhất thời thơ ấu của bạn là gì?",
    "Bạn sợ điều gì nhất?",
    "Điều điên rồ nhất bạn từng làm là gì?",
    "Bạn có tài lẻ nào không?",
    "Cuốn sách nào đã thay đổi cuộc đời bạn?",
    "Bạn thích mùa nào nhất trong năm?",
    "Nếu có siêu năng lực, bạn muốn năng lực gì?",
    "Bạn thích biển hay núi hơn?",
    "Bạn có tin vào định mệnh không?",
    "Điều gì làm bạn hạnh phúc nhất?",
    "Bạn đã bao giờ nhìn thấy ma chưa?",
    "Bạn thích trà hay cà phê?",
    "Bạn là người hướng nội hay hướng ngoại?",
    "Bài học lớn nhất bạn học được trong năm qua là gì?",
    "Bạn có muốn biết trước tương lai không?",
    "Nếu được quay lại quá khứ, bạn sẽ thay đổi điều gì?",
    "Chúc bạn một ngày tràn đầy năng lượng!",
]

def seed_bottles() -> None:
    # Always seed diverse messages regardless of count to ensure quality
    seeded_count = BottleEntity.find(BottleEntity.creator == SEED_SENTINEL).count()
    if seeded_count >= 200:
        return

    # To mix things up, we shuffle or just iterate. Simple list is fine.
    # We depend on Redis uniqueness check or just bulk insert checks
    
    # We want to fill up to 200
    # But since user asked for 200 diverse, we insert all 200 from the list
    
    # Check distinct content to avoid duplicates
    existing_bottles = BottleEntity.find(BottleEntity.creator == SEED_SENTINEL).all()
    existing_content = {b.content for b in existing_bottles}
    
    for content in BOTTLE_MESSAGES:
        if content not in existing_content:
            BottleEntity(
                type="text",
                content=content,
                creator=SEED_SENTINEL,
            ).save()
