from fastapi import status

AUTH_USER_EXISTS_ERROR = "auth_user_exists"
AUTH_INTERNAL_ERROR = "auth_internal_error"
AUTH_UNAUTHORIZED = "auth_unauthorized"
AUTH_USERNAME_INVALID = "username_invalid"
AUTH_PASSWORD_INVALID = "password_invalid"

AUTH_ERROR_STATUS = {
    AUTH_USER_EXISTS_ERROR: status.HTTP_409_CONFLICT,
    AUTH_INTERNAL_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
    AUTH_USERNAME_INVALID: status.HTTP_400_BAD_REQUEST,
    AUTH_PASSWORD_INVALID: status.HTTP_400_BAD_REQUEST,
    AUTH_UNAUTHORIZED: status.HTTP_401_UNAUTHORIZED,
}

